server:
  port: 9001
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lol_demo
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: lol-demo
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
file:
  dir: "E:\\java\\uploads\\"
  nginx-dir: "D:\\nginx-1.20.2\\html\\lol_equipment\\uploads"
